title: Luiz Chen Vieira
logo: assets/pfp.png
description: Data Scientist currently based in New Orleans (willing to relocate) and looking for an exciting start to my career!
#show_downloads: true
theme: jekyll-theme-minimal
