title: Luiz Chen Vieira
#logo: 
description: Data Scientist and Business Analyst Minor
#show_downloads: true
theme: jekyll-theme-minimal
profile_picture: "https://example.com/your_profile_picture.jpg"
